# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0
"""Tier 2: durable ledger signing key via the OS keychain (shard B1).

Source: the EC-4 / EC-9 durable-ledger-export slice. Per
``rules/facade-manager-detection.md`` Rule 1, ``load_or_create_ledger_key_manager``
has a Tier-2 wiring test asserting an externally-observable effect — here, that
a signing keypair generated by one "process" is reloaded by a *fresh* manager
over the SAME keychain backend, and that a signature produced before the
reload verifies against the reloaded public key (the cross-process EC-4
invariant the durable key exists to satisfy).

Per ``rules/testing.md`` Tier 2: real ``InMemoryKeyManager`` (real Ed25519
sign/verify); the keychain backend is dependency-injected (a pure-dict backend,
matching ``tests/tier1/test_connection_vault_adapter.py``) so the test exercises
the real persistence path without touching the host's OS keychain.
"""

from __future__ import annotations

import keyring.errors
import pytest
from kailash.trust.key_manager import InMemoryKeyManager

from envoy.ledger.keystore import (
    KEYRING_SERVICE_NAMESPACE,
    KEYRING_SERVICE_NAMESPACE_SESSION_ENC,
    LedgerKeyCorruptError,
    LedgerKeySchemaVersionError,
    LedgerKeystoreError,
    LedgerKeyUnavailableError,
    load_or_create_ledger_key_manager,
    load_or_create_session_encryption_key,
    principal_genesis_id,
)

SESSION_ENC_KEY_ID = "envoy-session-encryption-key"

SIGNING_KEY_ID = "envoy-digest-signing-key"
PRINCIPAL = "alice@example.com"
PAYLOAD = b"canonical-entry-bytes"


class _MemBackend:
    """Pure-dict keyring backend (mirrors the connection-vault test backend)."""

    def __init__(self) -> None:
        self._d: dict[tuple[str, str], str] = {}

    def set_password(self, service: str, username: str, password: str) -> None:
        self._d[(service, username)] = password

    def get_password(self, service: str, username: str) -> str | None:
        return self._d.get((service, username))

    def delete_password(self, service: str, username: str) -> None:
        key = (service, username)
        if key not in self._d:
            raise keyring.errors.PasswordDeleteError("not found")
        del self._d[key]


class _FailingBackend(_MemBackend):
    """Simulates an unavailable/locked OS keychain on every read/write."""

    def set_password(self, service: str, username: str, password: str) -> None:
        raise keyring.errors.KeyringError("keychain locked")

    def get_password(self, service: str, username: str) -> str | None:
        raise keyring.errors.KeyringError("keychain locked")


class _FixedRecordBackend(_MemBackend):
    """Returns a fixed (malformed) record for any read — tamper / version drift."""

    def __init__(self, record: str) -> None:
        super().__init__()
        self._record = record

    def get_password(self, service: str, username: str) -> str | None:
        return self._record


async def _load(backend: _MemBackend, principal: str = PRINCIPAL):
    return await load_or_create_ledger_key_manager(
        principal_id=principal,
        signing_key_id=SIGNING_KEY_ID,
        keyring_backend=backend,
    )


class TestLedgerKeystore:
    async def test_first_call_generates_persists_and_signs(self) -> None:
        backend = _MemBackend()
        mgr = await _load(backend)

        # External effect: a record now lives in the keychain backend under the
        # sha256(principal) account in the ledger-key namespace.
        account = f"{principal_genesis_id(PRINCIPAL)}:{SIGNING_KEY_ID}"
        assert backend.get_password(KEYRING_SERVICE_NAMESPACE, account) is not None

        # The manager can sign and exposes the public key (the facade caches it).
        pub = mgr.get_public_key(SIGNING_KEY_ID)
        assert pub is not None
        sig = mgr.sign_with_key(SIGNING_KEY_ID, PAYLOAD)
        assert await mgr.verify(PAYLOAD, sig, pub) is True

    async def test_reload_returns_same_key_cross_process(self) -> None:
        backend = _MemBackend()
        # "Process 1" generates + signs.
        mgr1 = await _load(backend)
        pub1 = mgr1.get_public_key(SIGNING_KEY_ID)
        sig1 = mgr1.sign_with_key(SIGNING_KEY_ID, PAYLOAD)

        # "Process 2" — a FRESH manager over the SAME keychain — reloads.
        mgr2 = await _load(backend)
        pub2 = mgr2.get_public_key(SIGNING_KEY_ID)

        assert pub2 == pub1  # same durable key, not a fresh random one
        # The signature from process 1 verifies under process 2's reloaded key —
        # this is the cross-process property EC-4 invariant 5/7 requires.
        assert await mgr2.verify(PAYLOAD, sig1, pub2) is True

    async def test_keychain_unavailable_is_fail_loud(self) -> None:
        # A locked/unavailable keychain MUST raise, never silently fall back to
        # an ephemeral key (which would make cross-process verification fail
        # without a trace).
        with pytest.raises(LedgerKeyUnavailableError):
            await _load(_FailingBackend())

    async def test_unparseable_record_is_fail_loud(self) -> None:
        # Present-but-unparseable (non-JSON) MUST raise corrupt, not regenerate
        # — a new key would orphan every entry signed by the original.
        with pytest.raises(LedgerKeyCorruptError):
            await _load(_FixedRecordBackend("not-json-{{{"))

    async def test_non_object_record_is_fail_loud(self) -> None:
        # Valid JSON that is not an object (e.g. a bare scalar) — corrupt.
        with pytest.raises(LedgerKeyCorruptError):
            await _load(_FixedRecordBackend('"42"'))

    async def test_missing_key_half_is_fail_loud(self) -> None:
        # Valid object, recognized schema, but missing a key half — corrupt.
        with pytest.raises(LedgerKeyCorruptError):
            await _load(_FixedRecordBackend('{"schema": "envoy-ledger-key/1"}'))

    async def test_unknown_schema_is_fail_loud(self) -> None:
        # Valid object with the key halves but an unrecognized schema version —
        # distinct error so the operator action is "upgrade Envoy", not "re-pair".
        with pytest.raises(LedgerKeySchemaVersionError):
            await _load(
                _FixedRecordBackend(
                    '{"schema": "envoy-ledger-key/2", "private_key": "x", "public_key": "y"}'
                )
            )

    async def test_invalid_signing_key_id_rejected(self) -> None:
        # A `:` in signing_key_id would shift the keyring account namespace.
        with pytest.raises(LedgerKeystoreError):
            await load_or_create_ledger_key_manager(
                principal_id=PRINCIPAL,
                signing_key_id="evil:key",
                keyring_backend=_MemBackend(),
            )

    async def test_distinct_principals_get_distinct_keys(self) -> None:
        backend = _MemBackend()
        mgr_a = await _load(backend, principal="alice@example.com")
        mgr_b = await _load(backend, principal="bob@example.com")
        assert mgr_a.get_public_key(SIGNING_KEY_ID) != mgr_b.get_public_key(SIGNING_KEY_ID)

    def test_kailash_public_keys_internal_attr_exists(self) -> None:
        # Pins the kailash-internals dependency the reload path relies on: if a
        # future kailash renames `_public_keys`, this fails HERE (loud, at the
        # module's own test) rather than as an opaque None-pubkey error several
        # call hops away in the facade.
        mgr = InMemoryKeyManager()
        assert isinstance(getattr(mgr, "_public_keys", None), dict)


async def _load_enc(backend: _MemBackend, principal: str = PRINCIPAL) -> bytes:
    return await load_or_create_session_encryption_key(
        principal_id=principal,
        key_id=SESSION_ENC_KEY_ID,
        keyring_backend=backend,
    )


class TestSessionEncryptionKeystore:
    """The S5o-enc payload-encryption key loader — mirrors the ledger signing
    key's keychain-gated, fail-loud lifecycle, for a raw 32-byte AES-256 key."""

    async def test_first_call_mints_persists_32_byte_key(self) -> None:
        backend = _MemBackend()
        key = await _load_enc(backend)
        assert isinstance(key, bytes) and len(key) == 32
        # External effect: a record lives under the SESSION-ENC namespace (NOT
        # the signing-key namespace — key separation).
        account = f"{principal_genesis_id(PRINCIPAL)}:{SESSION_ENC_KEY_ID}"
        assert backend.get_password(KEYRING_SERVICE_NAMESPACE_SESSION_ENC, account) is not None
        assert backend.get_password(KEYRING_SERVICE_NAMESPACE, account) is None

    async def test_reload_returns_same_key_cross_process(self) -> None:
        backend = _MemBackend()
        key1 = await _load_enc(backend)  # "process 1" mints
        key2 = await _load_enc(backend)  # "process 2" reloads
        assert key2 == key1  # durable, not a fresh random key each open

    async def test_distinct_principals_get_distinct_keys(self) -> None:
        backend = _MemBackend()
        ka = await _load_enc(backend, principal="alice@example.com")
        kb = await _load_enc(backend, principal="bob@example.com")
        assert ka != kb

    async def test_keychain_unavailable_is_fail_loud(self) -> None:
        with pytest.raises(LedgerKeyUnavailableError):
            await _load_enc(_FailingBackend())

    async def test_unparseable_record_is_fail_loud(self) -> None:
        with pytest.raises(LedgerKeyCorruptError):
            await _load_enc(_FixedRecordBackend("not-json-{{{"))

    async def test_missing_key_field_is_fail_loud(self) -> None:
        with pytest.raises(LedgerKeyCorruptError):
            await _load_enc(_FixedRecordBackend('{"schema": "envoy-session-enc-key/1"}'))

    async def test_non_base64_key_is_fail_loud(self) -> None:
        with pytest.raises(LedgerKeyCorruptError):
            await _load_enc(
                _FixedRecordBackend(
                    '{"schema": "envoy-session-enc-key/1", "key": "not base64 !!!"}'
                )
            )

    async def test_wrong_length_key_is_fail_loud(self) -> None:
        # base64 of 16 bytes (AES-128) — wrong size; MUST refuse, never use it.
        import base64

        short = base64.b64encode(b"\x00" * 16).decode("ascii")
        with pytest.raises(LedgerKeyCorruptError):
            await _load_enc(
                _FixedRecordBackend(
                    '{"schema": "envoy-session-enc-key/1", "key": "' + short + '"}'
                )
            )

    async def test_unknown_schema_is_fail_loud(self) -> None:
        with pytest.raises(LedgerKeySchemaVersionError):
            await _load_enc(
                _FixedRecordBackend(
                    '{"schema": "envoy-session-enc-key/2", "key": "AAAA"}'
                )
            )

    async def test_invalid_key_id_rejected(self) -> None:
        with pytest.raises(LedgerKeystoreError):
            await load_or_create_session_encryption_key(
                principal_id=PRINCIPAL, key_id="evil:key", keyring_backend=_MemBackend()
            )
