# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0
"""Tier-2 EnterpriseDeploymentRecord harness — REAL crypto, NO mocking.

Builds fully-valid + targeted-broken EDRs signed with a real kailash
`InMemoryKeyManager` (`rules/testing.md` Tier 2: real infrastructure, no
`@patch`/`MagicMock`). Every signature is a real Ed25519 signature over the
record's `signing_payload()` — the FULL canonical record digest, NOT the bare
`template_envelope_hash` — so the harness exercises the same transplant-resistant
binding the verifier checks (E-1).

Keys are seeded deterministically by `key_id` string (no time-dependent or
random material in the assertions — `rules/testing.md` Rules: deterministic),
but they are GENERATED by the key manager, not pasted constants
(`rules/security.md` § "test keys generated, not pasted").

`build_edr` signs the EXACT record it returns: it constructs the
`EnterpriseDeploymentRecord` (placeholder signatures), computes
`signing_payload()` over the real field set, signs that digest, and stamps the
signatures back in. So mutating any field via a `build_edr` override
automatically re-signs the mutated record — a test that wants a transplant
scenario uses `transplant_signatures_from` to KEEP a foreign record's signatures
on a mutated record instead.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from kailash.trust.key_manager import InMemoryKeyManager

from envoy.enterprise.schema import (
    EnterpriseDeploymentRecord,
    EnterprisePrincipal,
    EnterpriseScope,
)

# A fixed reference "now" so the 365-day window assertions are deterministic —
# tests inject this via the verifier's `now` callable and compute `enabled_at`
# relative to it (no wall-clock dependence).
REFERENCE_NOW = datetime(2026, 6, 10, 12, 0, 0, tzinfo=timezone.utc)

TEMPLATE_ENVELOPE_HASH = "sha256:1111111111111111111111111111111111111111111111111111111111111111"
ORG_GENESIS_HASH = "sha256:2222222222222222222222222222222222222222222222222222222222222222"

_ORG_ADMIN_ADDRESS = "pact:org-admin:acme"
_EMPLOYEE_ADDRESS = "pact:employee:jane"
_ORG_ID = "acme-corp"
_TEMPLATE_ENVELOPE_REF = "@org/enterprise-default-v1"


@dataclass
class EdrKeys:
    """The minted keypairs + the resolved org-roots map for one EDR scenario."""

    key_manager: InMemoryKeyManager
    org_root_pubkey: str
    employee_pubkey: str
    known_org_roots: Mapping[str, str]


def reference_now() -> datetime:
    """The injectable deterministic clock for the verifier (`now=` callable)."""
    return REFERENCE_NOW


def iso_days_ago(days: int) -> str:
    """An ISO-8601 `enabled_at` `days` before `REFERENCE_NOW` (UTC, trailing Z).

    Accepts NEGATIVE `days` to produce a FUTURE-dated `enabled_at` (used by the
    step-5 future-dated regression test).
    """
    moment = REFERENCE_NOW - timedelta(days=days)
    return moment.replace(microsecond=0).isoformat().replace("+00:00", "Z")


async def mint_edr_keys(
    *,
    org_genesis_hash: str = ORG_GENESIS_HASH,
) -> EdrKeys:
    """Generate the org Trust Lineage root key + the employee Genesis key.

    Signing happens later in `build_edr`, which signs the FULL canonical record
    digest (`signing_payload()`) — so the keys are minted here but the
    signatures are produced over the exact record the test assembles.
    """
    km = InMemoryKeyManager()
    _org_priv, org_root_pubkey = await km.generate_keypair("edr-org-root")
    _emp_priv, employee_pubkey = await km.generate_keypair("edr-employee-genesis")

    return EdrKeys(
        key_manager=km,
        org_root_pubkey=org_root_pubkey,
        employee_pubkey=employee_pubkey,
        known_org_roots={org_genesis_hash: org_root_pubkey},
    )


def _assemble_record(
    keys: EdrKeys,
    *,
    org_genesis_hash: str,
    template_envelope_hash: str,
    scope: str,
    verification_algorithm: str,
    enabled_at: str,
    employee_public_key_hex: str,
    org_admin_signature_hex: str,
    affected_employee_signature_hex: str,
) -> EnterpriseDeploymentRecord:
    """Construct an `EnterpriseDeploymentRecord` directly (bypassing the dual-sign
    gate in `from_dict`) so `signing_payload()` can be computed BEFORE the
    signatures exist. The scope string is resolved through the closed enum."""
    return EnterpriseDeploymentRecord(
        org_genesis_hash=org_genesis_hash,
        org_id=_ORG_ID,
        deploying_principal=EnterprisePrincipal(
            address=_ORG_ADMIN_ADDRESS, public_key_hex=keys.org_root_pubkey
        ),
        affected_employee_principal=EnterprisePrincipal(
            address=_EMPLOYEE_ADDRESS, public_key_hex=employee_public_key_hex
        ),
        template_envelope_hash=template_envelope_hash,
        template_envelope_ref=_TEMPLATE_ENVELOPE_REF,
        enabled_at=enabled_at,
        scope=EnterpriseScope.from_value(scope),
        verification_algorithm=verification_algorithm,
        org_admin_signature_hex=org_admin_signature_hex,
        affected_employee_signature_hex=affected_employee_signature_hex,
    )


def _record_to_wire(record: EnterpriseDeploymentRecord) -> dict[str, Any]:
    """Render a record back to the wire dict shape `from_dict` consumes."""
    return {
        "type": "EnterpriseDeploymentRecord",
        "schema_version": "edr/1.0",
        "org_genesis_hash": record.org_genesis_hash,
        "org_id": record.org_id,
        "deploying_principal": {
            "address": record.deploying_principal.address,
            "public_key_hex": record.deploying_principal.public_key_hex,
        },
        "affected_employee_principal": {
            "address": record.affected_employee_principal.address,
            "public_key_hex": record.affected_employee_principal.public_key_hex,
        },
        "template_envelope_hash": record.template_envelope_hash,
        "template_envelope_ref": record.template_envelope_ref,
        "enabled_at": record.enabled_at,
        "scope": record.scope.value,
        "verification_algorithm": record.verification_algorithm,
        "signatures": {
            "org_admin_signature_hex": record.org_admin_signature_hex,
            "affected_employee_signature_hex": record.affected_employee_signature_hex,
        },
    }


def build_edr(
    keys: EdrKeys,
    *,
    org_genesis_hash: str = ORG_GENESIS_HASH,
    template_envelope_hash: str = TEMPLATE_ENVELOPE_HASH,
    scope: str = EnterpriseScope.EMPLOYEE_PERSONAL_ENVELOPE_OVERLAY.value,
    verification_algorithm: str = "ed25519",
    enabled_at: str | None = None,
    sign_org_admin: bool = True,
    sign_employee: bool = True,
    org_admin_signature_hex: str | None = None,
    affected_employee_signature_hex: str | None = None,
    employee_public_key_hex: str | None = None,
) -> dict[str, Any]:
    """Assemble a wire EDR dict, signing the FULL canonical record digest.

    Defaults produce a fully-valid dual-signed `edr/1.0` record. The signatures
    are produced over `record.signing_payload()` (the full field set), so any
    field override automatically re-signs the mutated record — exactly what the
    transplant defense requires. To produce a single-signed record, pass
    `sign_org_admin=False` / `sign_employee=False` (yields an empty-string
    signature). To produce a FORGED signature (wrong key or wrong payload), pass
    `org_admin_signature_hex` / `affected_employee_signature_hex` explicitly —
    those override the genuine signature without re-signing.
    """
    employee_pubkey = (
        employee_public_key_hex if employee_public_key_hex is not None else keys.employee_pubkey
    )
    resolved_enabled_at = enabled_at if enabled_at is not None else iso_days_ago(1)

    # Build the record with placeholder signatures so signing_payload() (which
    # EXCLUDES the signatures block) can be computed over the real field set.
    draft = _assemble_record(
        keys,
        org_genesis_hash=org_genesis_hash,
        template_envelope_hash=template_envelope_hash,
        scope=scope,
        verification_algorithm=verification_algorithm,
        enabled_at=resolved_enabled_at,
        employee_public_key_hex=employee_pubkey,
        org_admin_signature_hex="",
        affected_employee_signature_hex="",
    )
    payload = draft.signing_payload().encode("utf-8")

    if org_admin_signature_hex is not None:
        org_sig = org_admin_signature_hex
    elif sign_org_admin:
        org_sig = keys.key_manager.sign_with_key("edr-org-root", payload)
    else:
        org_sig = ""

    if affected_employee_signature_hex is not None:
        emp_sig = affected_employee_signature_hex
    elif sign_employee:
        emp_sig = keys.key_manager.sign_with_key("edr-employee-genesis", payload)
    else:
        emp_sig = ""

    signed = _assemble_record(
        keys,
        org_genesis_hash=org_genesis_hash,
        template_envelope_hash=template_envelope_hash,
        scope=scope,
        verification_algorithm=verification_algorithm,
        enabled_at=resolved_enabled_at,
        employee_public_key_hex=employee_pubkey,
        org_admin_signature_hex=org_sig,
        affected_employee_signature_hex=emp_sig,
    )
    return _record_to_wire(signed)


def transplant_signatures(
    source_wire: dict[str, Any], target_wire: dict[str, Any]
) -> dict[str, Any]:
    """Lift the signatures from `source_wire` onto `target_wire`, unchanged.

    The transplant-attack primitive: produce an EDR carrying a DIFFERENT field
    set (e.g. a widened scope or a swapped employee) but the SAME signature pair
    as a legitimately dual-signed source. The verifier MUST reject it because the
    signatures cover the source's full record, not the target's.
    """
    out = dict(target_wire)
    out["signatures"] = dict(source_wire["signatures"])
    return out


__all__ = [
    "ORG_GENESIS_HASH",
    "REFERENCE_NOW",
    "TEMPLATE_ENVELOPE_HASH",
    "EdrKeys",
    "build_edr",
    "iso_days_ago",
    "mint_edr_keys",
    "reference_now",
    "transplant_signatures",
]
