# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0
"""Tier-2 EnterpriseDeploymentRecord harness — REAL crypto, NO mocking.

Builds fully-valid + targeted-broken EDRs signed with a real kailash
`InMemoryKeyManager` (`rules/testing.md` Tier 2: real infrastructure, no
`@patch`/`MagicMock`). Every signature is a real Ed25519 signature over the
`template_envelope_hash`, the same payload the verifier checks.

Keys are seeded deterministically by `key_id` string (no time-dependent or
random material in the assertions — `rules/testing.md` Rules: deterministic),
but they are GENERATED by the key manager, not pasted constants
(`rules/security.md` § "test keys generated, not pasted").
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from kailash.trust.key_manager import InMemoryKeyManager

from envoy.enterprise.schema import EnterpriseScope

# A fixed reference "now" so the 365-day window assertions are deterministic —
# tests inject this via the verifier's `now` callable and compute `enabled_at`
# relative to it (no wall-clock dependence).
REFERENCE_NOW = datetime(2026, 6, 10, 12, 0, 0, tzinfo=timezone.utc)

TEMPLATE_ENVELOPE_HASH = "sha256:1111111111111111111111111111111111111111111111111111111111111111"
ORG_GENESIS_HASH = "sha256:2222222222222222222222222222222222222222222222222222222222222222"


@dataclass
class EdrKeys:
    """The minted keypairs + the resolved org-roots map for one EDR scenario."""

    key_manager: InMemoryKeyManager
    org_root_pubkey: str
    employee_pubkey: str
    org_admin_signature_hex: str
    employee_signature_hex: str
    known_org_roots: Mapping[str, str]


def reference_now() -> datetime:
    """The injectable deterministic clock for the verifier (`now=` callable)."""
    return REFERENCE_NOW


def iso_days_ago(days: int) -> str:
    """An ISO-8601 `enabled_at` `days` before `REFERENCE_NOW` (UTC, trailing Z)."""
    moment = REFERENCE_NOW - timedelta(days=days)
    return moment.replace(microsecond=0).isoformat().replace("+00:00", "Z")


async def mint_edr_keys(
    *,
    template_envelope_hash: str = TEMPLATE_ENVELOPE_HASH,
    org_genesis_hash: str = ORG_GENESIS_HASH,
    sign_org_admin: bool = True,
    sign_employee: bool = True,
) -> EdrKeys:
    """Generate the org Trust Lineage root key + the employee Genesis key, sign.

    Both signatures are over `template_envelope_hash` (the canonical artifact the
    org admin and employee attest to). `sign_org_admin` / `sign_employee` let a
    test produce a single-signed record by withholding one signature (empty
    string) without changing the key material.
    """
    km = InMemoryKeyManager()
    _org_priv, org_root_pubkey = await km.generate_keypair("edr-org-root")
    _emp_priv, employee_pubkey = await km.generate_keypair("edr-employee-genesis")

    payload = template_envelope_hash.encode("utf-8")
    org_admin_signature_hex = km.sign_with_key("edr-org-root", payload) if sign_org_admin else ""
    employee_signature_hex = (
        km.sign_with_key("edr-employee-genesis", payload) if sign_employee else ""
    )

    return EdrKeys(
        key_manager=km,
        org_root_pubkey=org_root_pubkey,
        employee_pubkey=employee_pubkey,
        org_admin_signature_hex=org_admin_signature_hex,
        employee_signature_hex=employee_signature_hex,
        known_org_roots={org_genesis_hash: org_root_pubkey},
    )


def build_edr(
    keys: EdrKeys,
    *,
    org_genesis_hash: str = ORG_GENESIS_HASH,
    template_envelope_hash: str = TEMPLATE_ENVELOPE_HASH,
    scope: str = EnterpriseScope.EMPLOYEE_PERSONAL_ENVELOPE_OVERLAY.value,
    verification_algorithm: str = "ed25519",
    enabled_at: str | None = None,
    org_admin_signature_hex: str | None = None,
    affected_employee_signature_hex: str | None = None,
    employee_public_key_hex: str | None = None,
) -> dict[str, Any]:
    """Assemble a wire EDR dict from the minted keys + per-test overrides.

    Defaults produce a fully-valid dual-signed `edr/1.0` record; each keyword
    overrides exactly one field for a single-step-failure scenario.
    """
    return {
        "type": "EnterpriseDeploymentRecord",
        "schema_version": "edr/1.0",
        "org_genesis_hash": org_genesis_hash,
        "org_id": "acme-corp",
        "deploying_principal": {
            "address": "pact:org-admin:acme",
            "public_key_hex": keys.org_root_pubkey,
        },
        "affected_employee_principal": {
            "address": "pact:employee:jane",
            "public_key_hex": (
                employee_public_key_hex
                if employee_public_key_hex is not None
                else keys.employee_pubkey
            ),
        },
        "template_envelope_hash": template_envelope_hash,
        "template_envelope_ref": "@org/enterprise-default-v1",
        "enabled_at": enabled_at if enabled_at is not None else iso_days_ago(1),
        "scope": scope,
        "verification_algorithm": verification_algorithm,
        "signatures": {
            "org_admin_signature_hex": (
                org_admin_signature_hex
                if org_admin_signature_hex is not None
                else keys.org_admin_signature_hex
            ),
            "affected_employee_signature_hex": (
                affected_employee_signature_hex
                if affected_employee_signature_hex is not None
                else keys.employee_signature_hex
            ),
        },
    }


__all__ = [
    "ORG_GENESIS_HASH",
    "REFERENCE_NOW",
    "TEMPLATE_ENVELOPE_HASH",
    "EdrKeys",
    "build_edr",
    "iso_days_ago",
    "mint_edr_keys",
    "reference_now",
]
